name: Publish Weather Updates

on:
  workflow_dispatch: # Позволяет запускать рабочий процесс вручную из интерфейса GitHub
  schedule:
    # Запускать каждый день в 00:00 и 12:00 по UTC.
    # Это соответствует 07:00 и 19:00 по времени Пномпеня (GMT+7) без учета летнего времени.
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest # Запускать на чистой виртуальной машине Ubuntu

    steps:
    - name: Checkout repository # Шаг 1: Клонировать ваш репозиторий
      uses: actions/checkout@v4

    - name: Set up Python # Шаг 2: Настроить среду Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Рекомендуется указывать конкретную версию Python

    - name: Install dependencies # Шаг 3: Установить необходимые библиотеки
      run: |
        pip install requests python-telegram-bot Pillow httpx

    - name: Install Noto Color Emoji font # Шаг 4: Установить системный шрифт для эмодзи
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-color-emoji
        sudo fc-cache -f -v # Принудительно обновить кэш шрифтов Fontconfig (необязательно, но полезно)

    - name: Create backgrounds folders # Шаг 5: Создать папки для фонов, если их нет (важно для правильной работы скрипта)
      run: |
        mkdir -p backgrounds/Пномпень
        mkdir -p backgrounds/Сиануквиль
        mkdir -p backgrounds/Сиемреап
        # Примечание: Убедитесь, что ваши фоновые изображения находятся в этих папках
        # в репозитории GitHub (т.е. закоммичены и запушены).

    - name: Run Python script # Шаг 6: Запустить ваш Python-скрипт
      env:
        # Передаем секреты GitHub в переменные окружения для скрипта
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        ACCUWEATHER_API_KEY: ${{ secrets.ACCUWEATHER_API_KEY }}
        TARGET_CHAT_ID: ${{ secrets.TARGET_CHAT_ID }}
        # TEST_MODE: "True" # Если хотите управлять тестовым режимом из YML, раскомментируйте
      run: python weather_publisher.py
