name: Delete Old Telegram Messages

on:
  workflow_dispatch:
  schedule:
    # Это соответствует 11:00, 17:00 и 23:00 по времени Пномпеня (GMT+7) без учета летнего времени.
    - cron: '0 4,10,16 * * *'
jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot==20.3 PyYAML==6.0

      - name: Run deletion script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TARGET_CHAT_ID: ${{ secrets.TARGET_CHAT_ID }}
        run: python delete_messages.py
