name: Delete Old Telegram Messages

on:
  schedule:
    - cron: '*/15 * * * *' # Запускать каждые 15 минут

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install python-telegram-bot PyYAML

      - name: Run deletion script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TARGET_CHAT_ID: ${{ secrets.TARGET_CHAT_ID }}
        run: python delete_messages.py
