name: Delete Old Weather Messages

on:
  schedule:
    - cron: '05 * * * *' 
  workflow_dispatch:
  push: # Добавляем триггер на push
    branches:
      - main # Или master, в зависимости от вашей основной ветки
    paths:
      - 'messages_to_delete.json' # Отслеживаем изменения в этом файле
    
jobs:
  delete:
    runs-on: ubuntu-latest
    
    # Отменяем предыдущие запуски, если они ещё выполняются (например, от ручного триггера)
    # Это может быть полезно, чтобы избежать одновременных запусков, если файл изменится несколько раз быстро
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout repository
      # Используем actions/checkout@v4 с токеном, чтобы Git-операции работали корректно
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Важно: передаем токен для checkout

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install python-telegram-bot httpx

    - name: Run Delete Old Messages Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        MESSAGES_TO_DELETE_FILE_NAME: messages_to_delete.json 
        DELETE_AFTER_HOURS_SETTING: 3
        # Передаём GITHUB_TOKEN в скрипт
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        python delete_messages_script.py
