name: Publish Weather Updates

on:
  workflow_dispatch: # Позволяет запускать рабочий процесс вручную
  schedule:
    # Запуск в 05:50, 11:50 и 17:50 по времени Пномпеня (UTC+7)
    - cron: '50 22,4,10 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Права на запись для коммита файла message_ids.yml
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests python-telegram-bot Pillow PyYAML

    - name: Create backgrounds folders
      run: |
        # Название папки должно соответствовать переменной BACKGROUNDS_FOLDER в скрипте
        mkdir -p backgrounds2/Пномпень
        mkdir -p backgrounds2/Сиануквиль
        mkdir -p backgrounds2/Сиемреап

    - name: Run Python script
      env:
        # Передаем секреты GitHub в переменные окружения для скрипта
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }} # <-- ИСПРАВЛЕНО
        TARGET_CHAT_ID: ${{ secrets.TARGET_CHAT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_MODE: "False"
      run: python weather_publisher.py

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add message_ids.yml
        if ! git diff --cached --quiet; then
          git commit -m "chore: Update message IDs"
          git pull --rebase
          git push
        else
          echo "✅ message_ids.yml unchanged"
        fi
